### ISSUE TITLE
No such customer: *ID*

### ISSUE THREAD

**Issue by escape75** [Glench/ExtPay#269]
When a developer checks his activated extension via:

https://extensionpay.com/extension/new-tab-start-page/api/v2/user?api_key=???

it says "paid: true" but ... openLoginPage() and openPaymentPage() calls:

https://extensionpay.com/extension/new-tab-start-page/manage-plan?api_key=???

and opens this error page:

No such customer: '???'; a similar object exists in test mode, but a live mode key was used to make this request.

**Comment by Glench** [comment]
Please list the EXACT steps you used in order to see this error.

**Comment by Glench** [comment]
Also, please email me with the api key of the user you're referring to and I can look into it more deeply.

**Comment by escape75** [comment]
Hello!

The current API key is c285e0fa-46ca-455e-a0ba-7bae394aa3ce ...
The error is: "No such customer: 'cus_S0N7gInOqJhn2M'; a similar object
exists in test mode, but a live mode key was used to make this request."

It seems to always happen when the extension is the developer's own
extension, I'm guessing there's no transaction actually there to lookup,
however in 3.0.7 it was working correctly.
It actually works fine until the extension is activated via the magic link,
makes sense as then it's actually registered to the developer ...

The account is under ***@***.***, it happens when I call
"extpay.openLoginPage()" from the extension's options page.

Thanks for looking into it!

Martin

**Comment by Glench** [comment]
Ah, this was because you were logging in to a dev account while in live mode. I just deployed a fix so this won't be allowed anymore.

**Comment by escape75** [comment]
Thanks for looking into this!

Now I've added a 'free user' via the dashboard (same email as developer) and the error is now:

"400
No configuration provided and your live mode default configuration has not been created. Provide a configuration or create your default by saving your customer portal settings in live mode at https://dashboard.stripe.com/settings/billing/portal."

Do we really need to have 2 separate email addresses, one for developer login and one for extension activation ?

Thanks!

**Comment by escape75** [comment]
Additionally when a free user is added in dashboard and the user logs in via the extension (extpay.openLoginPage) to activate, this error is shown in subsequent login (extpay.openLoginPage) attempts:

"400
No configuration provided and your live mode default configuration has not been created. Provide a configuration or create your default by saving your customer portal settings in live mode at https://dashboard.stripe.com/settings/billing/portal."

Thanks!

**Comment by Glench** [comment]
Did you activate your Stripe billing portal at the link?

**Comment by escape75** [comment]
Yes, my stripe portal is setup and working fine, it's been working fine before the extension was updated...

I just created a free user 'martin at sermak.ca' and after I activate via magic link I still see the 400 error,
so it looks like all free customers would see that error even though they are technically activated.
To see the error just open the login page (openLoginPage) after the extension has been activated.

Thanks!

**Comment by escape75** [comment]
I was able to fix it by activating the "Customer portal link" in Stripe, under Settings and Billing and Customer Portal.
